module.exports = [
  "history",
  "lodash",
  "prop-types",
  "react",
  "react-dnd",
  "react-dnd-html5-backend",
  "react-dom",
  "react-redux",
  "react-router",
  "react-router-dom",
  "react-router-redux",
  "redux",
  "redux-actions",
  "redux-logger",
  "reselect",
];
