export default {
  INCREASEMENT: 'INCREASEMENT',
  DECREASEMENT: 'DECREASEMENT',
  ASYNC_INCREASEMENT: 'ASYNC_INCREASEMENT',
  FETCH_NUMBERS: 'FETCH_NUMBERS',

  ADD_STUDENT: 'ADD_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT'
};
